name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "tag"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.0.${{github.run_id}}"
          prerelease: false